
const token='__TOKEN__';const $=id=>document.getElementById(id);let files=[],busy=false;
async function api(path,data={}){let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Tay-Token':token},body:JSON.stringify(data)});let j=await r.json();if(j.error)throw Error(j.error);return j}
function status(t){$('status').textContent=t}
async function copyText(text,button){try{await navigator.clipboard.writeText(text);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1200)}catch(e){status('Clipboard unavailable. Select the message text and press Command+C.')}}
function msg(role,text,target=$('messages')){let wrap=document.createElement('div');wrap.className='msg '+role;let who=document.createElement('div');who.className='who';who.textContent=role==='assistant'?'TAY':'YOU';wrap.append(who);let content=document.createElement('div');content.textContent=text;wrap.append(content);let actions=document.createElement('div');actions.className='message-actions';let copy=document.createElement('button');copy.textContent='Copy';copy.setAttribute('aria-label','Copy '+(role==='assistant'?'Tay reply':'your message'));copy.onclick=()=>copyText(text,copy);actions.append(copy);let reuse=document.createElement('button');reuse.textContent=role==='user'?'Edit & reuse':'Use in message';reuse.onclick=()=>{$('prompt').value=text;$('prompt').focus();$('historyDialog').close()};actions.append(reuse);if(role==='assistant'){let b=document.createElement('button');b.textContent='Read aloud';b.onclick=async()=>{try{stopMic('Microphone off during voice playback.');status('Preparing voice…');await api('/speak',{text,voice:$('voice').value,key:$('voiceKey').value,voice_id:$('voiceId').value,paid:$('voicePaid').checked});status('Playing response.')}catch(e){status(e.message)}};actions.append(b)}wrap.append(actions);target.append(wrap);target.scrollTop=target.scrollHeight}

async function load(project){let s=await api('/state',{project});$('project').replaceChildren();s.projects.forEach(p=>{let o=new Option(p.split('/').pop(),p);$('project').add(o)});$('project').value=s.project;$('projectName').textContent=s.project.split('/').pop();$('messages').replaceChildren();if(!s.messages.length){let w=document.createElement('div');w.className='welcome';let h=document.createElement('h1');h.textContent='What shall we work on?';let p=document.createElement('p');p.textContent='I’m Tay. Choose a project, ask a question, or attach a text file. Use Coding tools when you’re ready to edit and build.';w.append(h,p);$('messages').append(w)}s.messages.forEach(m=>msg(m.role,m.content));files=[];$('attachments').textContent=''}
$('project').onchange=()=>load($('project').value).catch(e=>status(e.message));
$('new').onclick=async()=>{try{await api('/new',{project:$('project').value});await load($('project').value)}catch(e){status(e.message)}};
$('add').onclick=async()=>{let p=prompt('Paste the full path to a local project folder:');if(p)try{let s=await api('/add',{project:p});await load(s.project)}catch(e){status(e.message)}};
$('engines').onclick=async()=>{try{let e=await api('/engines');$('engineState').textContent='Installed Unity: '+e.unity_editors.join(', ')+'. Installed Unreal: '+e.unreal_editors.join(', ')+'. '+e.note;$('engineDialog').showModal()}catch(e){status(e.message)}};$('engineClose').onclick=()=>$('engineDialog').close();for(const [id,kind] of [['unityOpen','unity'],['unrealOpen','unreal'],['unityHub','unity-hub'],['epicOpen','epic']]){$(id).onclick=async()=>{try{let r=await api('/engine-open',{kind,project:$('project').value});$('engineState').textContent=r.message}catch(e){$('engineState').textContent=e.message}}}
$('connections').onclick=()=>$('settings').showModal();$('save').onclick=()=>{$('settings').close();$('modeLabel').textContent=$('mode').selectedOptions[0].text};
$('tools').onclick=()=>api('/tools').then(()=>status('Coding tools opened in Terminal. Choose your project there.')).catch(e=>status(e.message));
$('attach').onclick=()=>{let p=prompt('Text file path relative to this project, e.g. project.godot (max 40 KB). Only attached files are read by chat.');if(p){files.push(p);$('attachments').textContent=files.join(' · ')}};
async function send(){if(busy||!$('prompt').value.trim())return;if(await shortcut($('prompt').value.trim()))return;stopMic();busy=true;$('send').disabled=true;$('project').disabled=true;$('new').disabled=true;$('add').disabled=true;let text=$('prompt').value;$('prompt').value='';document.querySelector('.welcome')?.remove();msg('user',text);status('Tay is thinking… local models can take a few minutes.');try{let j=await api('/chat',{project:$('project').value,message:text,files,mode:$('mode').value,model:$('model').value,key:$('key').value,paid:$('paid').checked});while(true){await new Promise(r=>setTimeout(r,1500));let s=await api('/job',{job:j.job});if(s.done){msg('assistant',s.answer);status('');break}}}catch(e){status(e.message);$('prompt').value=text}finally{busy=false;$('send').disabled=false;$('project').disabled=false;$('new').disabled=false;$('add').disabled=false}}
$('send').onclick=send;$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};load().catch(e=>status(e.message));

async function showFoundry(){const data=await api('/foundry');$('ideaList').replaceChildren();if(!data.items.length)$('ideaList').textContent='No opportunities captured yet.';for(const item of data.items){let card=document.createElement('section');card.className='idea-card';let title=document.createElement('h3');title.textContent=item.title;card.append(title);let desc=document.createElement('p');desc.textContent=item.details.problem||'Problem not yet recorded';card.append(desc);let sel=document.createElement('select');sel.setAttribute('aria-label','Stage for '+item.title);data.stages.forEach(stage=>sel.add(new Option(stage,stage)));sel.value=item.stage;sel.onchange=async()=>{try{await api('/opportunity-update',{id:item.id,stage:sel.value});$('foundryStatus').textContent='Stage saved. No build started.'}catch(e){$('foundryStatus').textContent=e.message}};card.append(sel);let details=document.createElement('details');let summary=document.createElement('summary');summary.textContent='Opportunity details';details.append(summary);let info=document.createElement('pre');info.textContent=Object.entries(item.details).map(([k,v])=>k.replaceAll('_',' ')+': '+(v??'Unknown — needs evidence')).join('\n');details.append(info);card.append(details);$('ideaList').append(card)}$('foundryDialog').showModal()}
$('foundry').onclick=()=>showFoundry().catch(e=>status(e.message));$('foundryClose').onclick=()=>$('foundryDialog').close();
$('ideaForm').onsubmit=async e=>{e.preventDefault();try{await api('/opportunity',{title:$('ideaTitle').value,problem:$('ideaProblem').value,target_customer:$('ideaCustomer').value,evidence:$('ideaEvidence').value,source:$('project').value});$('ideaForm').reset();$('foundryStatus').textContent='Captured. Validate before building.';await showFoundry()}catch(e){$('foundryStatus').textContent=e.message}};
$('historyClose').onclick=()=>$('historyDialog').close();$('historyButton').onclick=async()=>{try{const d=await api('/archives',{project:$('project').value});$('historyList').replaceChildren();$('historyMessages').replaceChildren();if(!d.items.length)$('historyList').textContent='No archived conversations yet. New conversation preserves the previous chat here.';for(const item of d.items){let b=document.createElement('button');b.textContent=new Date(item.date*1000).toLocaleString();b.onclick=async()=>{try{let chat=await api('/archive-read',{project:$('project').value,id:item.id});$('historyMessages').replaceChildren();chat.messages.forEach(m=>msg(m.role,m.content,$('historyMessages')))}catch(e){status(e.message)}};$('historyList').append(b)}$('historyDialog').showModal()}catch(e){status(e.message)}};
$('exportChat').onclick=async()=>{try{let d=await api('/state',{project:$('project').value});let text=d.messages.map(m=>(m.role==='user'?'YOU':'TAY')+'\n'+m.content).join('\n\n');let url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));let a=document.createElement('a');a.href=url;a.download='Transcenlutions-chat.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){status(e.message)}};
async function shortcut(text){let t=text.toLowerCase().replace(/[.!?]+$/,'');let action=null;
const panels={'open connections':'connections','show connections':'connections','open settings':'connections','open voice settings':'connections','open microphone settings':'micOptions','open venture foundry':'foundry','show opportunities':'foundry','open conversation history':'historyButton','export conversation':'exportChat','open coding tools':'tools','show engine settings':'engines'};
if(panels[t])action=async()=>{$(panels[t]).click();return 'Opened '+t.replace(/^(open|show) /,'')+'.'};
else if(t==='use local mode'||t==='switch to local mode')action=async()=>{$('mode').value='local';$('paid').checked=false;$('modeLabel').textContent='Local — no API charges';return 'Local chat mode selected.'};
else if(t==='switch to a free model')action=async()=>{$('mode').value='free';$('paid').checked=false;$('modeLabel').textContent='Free online — OpenRouter';$('settings').showModal();return 'Free online mode selected. Enter your OpenRouter key to use it. No paid fallback.'};
else if(t==='open this project in unity'||t==='open this project in unreal')action=async()=>{let r=await api('/engine-open',{project:$('project').value,kind:t.endsWith('unity')?'unity':'unreal'});return r.message};
else if(/^capture (?:an )?idea:/i.test(text))action=async()=>{let title=text.slice(text.indexOf(':')+1).trim();await api('/opportunity',{title,source:$('project').value});return 'Captured “'+title+'” in Venture Foundry. No development project was created.'};
else if(t==='what can you do'||t==='help')action=async()=> 'Chat shortcuts: Open connections; Open voice settings; Open microphone settings; Open Venture Foundry; Capture idea: [idea]; Open conversation history; Export conversation; Open coding tools; Open this project in Unity; Open this project in Unreal; Use local mode; Switch to a free model. Other requests go to the selected model. Autonomous code execution, full desktop control and lip-sync are not connected to this chat yet.';
if(!action)return false;busy=true;stopMic();$('prompt').value='';document.querySelector('.welcome')?.remove();msg('user',text);try{let answer=await action();msg('assistant',answer);await api('/record-action',{project:$('project').value,message:text,answer})}catch(e){msg('assistant',e.message)}finally{busy=false}return true}

// Browser speech recognition is optional, session-only, and off on page load.
const SpeechAPI=window.SpeechRecognition||window.webkitSpeechRecognition;
let recognition=null,micActive=false,micStarting=false;
function addressedSpeech(text){const match=text.trim().match(/^(?:hey\s+tay|hey\s+Tay|okay\s+tay|ok\s+tay)[,.:!?\s]+(.+)$/i);return match?match[1].trim():null}
function micNote(text){$('micStatus').textContent=text}
function stopMic(reason='Microphone off.'){micActive=false;micStarting=false;if(recognition){const old=recognition;recognition=null;old.onend=null;old.onresult=null;try{old.abort()}catch(e){}}$('mic').textContent='🎙 Talk';$('mic').setAttribute('aria-pressed','false');micNote(reason)}
function startMic(){
 if(micActive||micStarting){stopMic();return}
 if(!SpeechAPI){micNote('Speech recognition is unavailable here. Open Tay.app in Chrome, or keep typing.');return}
 if(!$('speechConsent').checked){$('micSettings').showModal();return}
 if(busy){micNote('Wait for Tay to finish before starting the microphone.');return}
 const wake=$('micMode').value==='wake';const r=new SpeechAPI();recognition=r;micStarting=true;
 r.lang='en-US';r.continuous=wake;r.interimResults=true;r.maxAlternatives=1;
 r.onstart=()=>{if(recognition!==r)return;micStarting=false;micActive=true;$('mic').textContent='■ Stop mic';$('mic').setAttribute('aria-pressed','true');micNote(wake?'Listening — begin each request with “Hey Tay”.':'Listening — speak your message. It will appear for review.')};
 r.onresult=event=>{if(recognition!==r||!micActive)return;for(let i=event.resultIndex;i<event.results.length;i++){
   const result=event.results[i];if(!result.isFinal)continue;
   const transcript=result[0].transcript.trim();const accepted=wake?addressedSpeech(transcript):transcript;
   if(!accepted){micNote('Listening for “Hey Tay” at the start of a request.');continue}
   $('prompt').value=[$('prompt').value.trim(),accepted].filter(Boolean).join(' ');
   stopMic('Message captured. Review it, then press Send.');$('prompt').focus();break;
 }};
 r.onerror=event=>{const errors={'not-allowed':'Microphone permission was denied. Allow it in Chrome’s site settings, then try again.','service-not-allowed':'Browser speech service is unavailable. Try Tay.app in Chrome.','network':'Speech service could not connect. Browser recognition may need internet.','audio-capture':'No microphone was available. Check your Mac input settings.','no-speech':'No speech detected. Tap Talk to try again.'};stopMic(errors[event.error]||'Microphone stopped: '+event.error)};
 r.onend=()=>{if(recognition===r)stopMic('Microphone off. Tap Talk to listen again.')};
 micNote('Requesting microphone access…');try{r.start()}catch(e){stopMic('Could not start microphone: '+e.message)}
}
$('mic').onclick=startMic;$('micOptions').onclick=()=>$('micSettings').showModal();
$('micDone').onclick=()=>{$('micSettings').close();stopMic();};
$('speechConsent').onchange=()=>{if(!$('speechConsent').checked)stopMic()};
$('micMode').onchange=()=>stopMic();
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMic('Microphone off while Tay is in the background.')});
window.addEventListener('pagehide',()=>stopMic());
if(!SpeechAPI)micNote('Use Tay.app in Chrome for microphone support.');

