from pathlib import Path
root=Path(__file__).parent;p=root/'index.html';s=p.read_text()
s=s.replace('<title>Tay Command</title>','<title>Transcenlutions · Tay Command</title>').replace('<div class="brand">TAY<span> COMMAND</span></div>','<div class="brand">TRANSCENLUTIONS<span> TAY COMMAND</span></div>')
s=s.replace('<button id="engines">Unity · Unreal · Xbox</button>','<button id="engines">Unity · Unreal · Xbox</button><button id="foundry">Venture Foundry</button><button id="historyButton">Conversation history</button><button id="exportChat">Export conversation</button>')
s=s.replace('<dialog id="micSettings">','''<dialog id="foundryDialog"><h2>Venture Foundry</h2><p class="note">Capture broadly. Validate with evidence. Build selectively. Capturing or changing a stage never creates a development project.</p><form id="ideaForm"><label for="ideaTitle">Opportunity</label><input id="ideaTitle" required><label for="ideaProblem">Problem</label><textarea id="ideaProblem"></textarea><label for="ideaCustomer">Target customer</label><input id="ideaCustomer"><label for="ideaEvidence">Evidence / source</label><textarea id="ideaEvidence"></textarea><button type="submit">Capture opportunity</button></form><p id="foundryStatus" role="status"></p><div id="ideaList"></div><button id="foundryClose">Done</button></dialog><dialog id="historyDialog"><h2>Saved conversations</h2><p class="note">Archived conversations are read-only. Copy a message to reuse it in the current chat.</p><div id="historyList"></div><div id="historyMessages"></div><button id="historyClose">Done</button></dialog><dialog id="micSettings">''')
start=s.index('function msg(role,text)');end=s.index('\nasync function load',start)
s=s[:start]+'''async function copyText(text,button){try{await navigator.clipboard.writeText(text);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1200)}catch(e){status('Clipboard unavailable. Select the message text and press Command+C.')}}
function msg(role,text,target=$('messages')){let wrap=document.createElement('div');wrap.className='msg '+role;let who=document.createElement('div');who.className='who';who.textContent=role==='assistant'?'TAY':'YOU';wrap.append(who);let content=document.createElement('div');content.textContent=text;wrap.append(content);let actions=document.createElement('div');actions.className='message-actions';let copy=document.createElement('button');copy.textContent='Copy';copy.setAttribute('aria-label','Copy '+(role==='assistant'?'Tay reply':'your message'));copy.onclick=()=>copyText(text,copy);actions.append(copy);let reuse=document.createElement('button');reuse.textContent=role==='user'?'Edit & reuse':'Use in message';reuse.onclick=()=>{$('prompt').value=text;$('prompt').focus();$('historyDialog').close()};actions.append(reuse);if(role==='assistant'){let b=document.createElement('button');b.textContent='Read aloud';b.onclick=async()=>{try{stopMic('Microphone off during voice playback.');status('Preparing voice…');await api('/speak',{text,voice:$('voice').value,key:$('voiceKey').value,voice_id:$('voiceId').value,paid:$('voicePaid').checked});status('Playing response.')}catch(e){status(e.message)}};actions.append(b)}wrap.append(actions);target.append(wrap);target.scrollTop=target.scrollHeight}
''' +s[end:]
s=s.replace("async function send(){if(busy||!$('prompt').value.trim())return;", "async function send(){if(busy||!$('prompt').value.trim())return;if(await shortcut($('prompt').value.trim()))return;")
extra='''
async function showFoundry(){const data=await api('/foundry');$('ideaList').replaceChildren();if(!data.items.length)$('ideaList').textContent='No opportunities captured yet.';for(const item of data.items){let card=document.createElement('section');card.className='idea-card';let title=document.createElement('h3');title.textContent=item.title;card.append(title);let desc=document.createElement('p');desc.textContent=item.details.problem||'Problem not yet recorded';card.append(desc);let sel=document.createElement('select');sel.setAttribute('aria-label','Stage for '+item.title);data.stages.forEach(stage=>sel.add(new Option(stage,stage)));sel.value=item.stage;sel.onchange=async()=>{try{await api('/opportunity-update',{id:item.id,stage:sel.value});$('foundryStatus').textContent='Stage saved. No build started.'}catch(e){$('foundryStatus').textContent=e.message}};card.append(sel);let details=document.createElement('details');let summary=document.createElement('summary');summary.textContent='Opportunity details';details.append(summary);let info=document.createElement('pre');info.textContent=Object.entries(item.details).map(([k,v])=>k.replaceAll('_',' ')+': '+(v??'Unknown — needs evidence')).join('\\n');details.append(info);card.append(details);$('ideaList').append(card)}$('foundryDialog').showModal()}
$('foundry').onclick=()=>showFoundry().catch(e=>status(e.message));$('foundryClose').onclick=()=>$('foundryDialog').close();
$('ideaForm').onsubmit=async e=>{e.preventDefault();try{await api('/opportunity',{title:$('ideaTitle').value,problem:$('ideaProblem').value,target_customer:$('ideaCustomer').value,evidence:$('ideaEvidence').value,source:$('project').value});$('ideaForm').reset();$('foundryStatus').textContent='Captured. Validate before building.';await showFoundry()}catch(e){$('foundryStatus').textContent=e.message}};
$('historyClose').onclick=()=>$('historyDialog').close();$('historyButton').onclick=async()=>{try{const d=await api('/archives',{project:$('project').value});$('historyList').replaceChildren();$('historyMessages').replaceChildren();if(!d.items.length)$('historyList').textContent='No archived conversations yet. New conversation preserves the previous chat here.';for(const item of d.items){let b=document.createElement('button');b.textContent=new Date(item.date*1000).toLocaleString();b.onclick=async()=>{try{let chat=await api('/archive-read',{project:$('project').value,id:item.id});$('historyMessages').replaceChildren();chat.messages.forEach(m=>msg(m.role,m.content,$('historyMessages')))}catch(e){status(e.message)}};$('historyList').append(b)}$('historyDialog').showModal()}catch(e){status(e.message)}};
$('exportChat').onclick=async()=>{try{let d=await api('/state',{project:$('project').value});let text=d.messages.map(m=>(m.role==='user'?'YOU':'TAY')+'\\n'+m.content).join('\\n\\n');let url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));let a=document.createElement('a');a.href=url;a.download='Transcenlutions-chat.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){status(e.message)}};
async function shortcut(text){let t=text.toLowerCase().replace(/[.!?]+$/,'');let action=null;
const panels={'open connections':'connections','show connections':'connections','open settings':'connections','open voice settings':'connections','open microphone settings':'micOptions','open venture foundry':'foundry','show opportunities':'foundry','open conversation history':'historyButton','export conversation':'exportChat','open coding tools':'tools','show engine settings':'engines'};
if(panels[t])action=async()=>{$(panels[t]).click();return 'Opened '+t.replace(/^(open|show) /,'')+'.'};
else if(t==='use local mode'||t==='switch to local mode')action=async()=>{$('mode').value='local';$('paid').checked=false;$('modeLabel').textContent='Local — no API charges';return 'Local chat mode selected.'};
else if(t==='switch to a free model')action=async()=>{$('mode').value='free';$('paid').checked=false;$('modeLabel').textContent='Free online — OpenRouter';$('settings').showModal();return 'Free online mode selected. Enter your OpenRouter key to use it. No paid fallback.'};
else if(t==='open this project in unity'||t==='open this project in unreal')action=async()=>{let r=await api('/engine-open',{project:$('project').value,kind:t.endsWith('unity')?'unity':'unreal'});return r.message};
else if(/^capture (?:an )?idea:/i.test(text))action=async()=>{let title=text.slice(text.indexOf(':')+1).trim();await api('/opportunity',{title,source:$('project').value});return 'Captured “'+title+'” in Venture Foundry. No development project was created.'};
else if(t==='what can you do'||t==='help')action=async()=> 'Chat shortcuts: Open connections; Open voice settings; Open microphone settings; Open Venture Foundry; Capture idea: [idea]; Open conversation history; Export conversation; Open coding tools; Open this project in Unity; Open this project in Unreal; Use local mode; Switch to a free model. Other requests go to the selected model. Autonomous code execution, full desktop control and lip-sync are not connected to this chat yet.';
if(!action)return false;busy=true;stopMic();$('prompt').value='';document.querySelector('.welcome')?.remove();msg('user',text);try{let answer=await action();msg('assistant',answer);await api('/record-action',{project:$('project').value,message:text,answer})}catch(e){msg('assistant',e.message)}finally{busy=false}return true}
'''
s=s.replace('// Browser speech recognition',extra+'\n// Browser speech recognition')
css='''
:root{--gold:#e6c47f;--purple:#391b59;--edge:rgba(225,193,128,.38)}body{background:radial-gradient(ellipse at 80% 0%,#27133c 0%,#111018 55%);color:#f4eee5}aside{background:linear-gradient(145deg,rgba(45,30,59,.8),rgba(8,8,13,.96));border-color:var(--edge);overflow:auto}.brand{font-size:16px;letter-spacing:1.5px;color:var(--gold)}.brand span{display:block;font-size:10px;letter-spacing:3px;margin-top:8px}header{background:linear-gradient(120deg,#28202d99,#131019cc);border-color:var(--edge)}
button,select,summary,a{background:linear-gradient(165deg,rgba(255,255,255,.25) 0%,rgba(190,157,220,.1) 42%,rgba(8,5,15,.75) 53%,rgba(116,72,157,.22) 100%);border:1px solid var(--edge);box-shadow:inset 0 1px 0 #ffffff70,inset 0 -1px 0 #0009,0 4px 14px #0005;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);color:#f1deaf;border-radius:10px;transition:background .18s,box-shadow .18s,transform .18s}
button:hover,summary:hover,a:hover{background:linear-gradient(165deg,#fff6,#75509e44 45%,#150d22dd 55%,#ba944a55);box-shadow:inset 0 1px 0 #fff9,0 0 16px #b786e333}button:active{transform:translateY(1px)}button:focus-visible,a:focus-visible,summary:focus-visible,select:focus-visible{outline:2px solid #f5d18a;outline-offset:3px}.send{background:linear-gradient(165deg,#fff4d5,#d4ae5d 43%,#6b481e 53%,#dfb665);color:#1c120b}.box,input,textarea{background-color:#21192c55}.box{border-color:var(--edge);box-shadow:inset 0 1px #ffffff20,0 12px 36px #0003}.msg.user{background:linear-gradient(145deg,#47255a99,#1f1829cc);border:1px solid #9564b344}.message-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.message-actions button{font-size:11px;padding:6px 10px}dialog{background:linear-gradient(140deg,#32203e,#111018 80%);border-color:var(--edge);box-shadow:0 20px 80px #000b}a,summary{display:inline-block;padding:8px 12px}input[type=checkbox]{appearance:none;width:17px;height:17px;border:1px solid var(--gold);background:linear-gradient(145deg,#fff6,#21132e);padding:0;vertical-align:middle;cursor:pointer}input[type=checkbox]:checked{background:linear-gradient(145deg,#fff0c1,#bc8d39);box-shadow:0 0 8px #d9b78077}select option{background:#21172a}.idea-card{padding:14px;margin:12px 0;border:1px solid var(--edge);border-radius:12px}.idea-card pre{white-space:pre-wrap;font-size:12px;line-height:1.7}.brand-art{animation:royal-presence 8s ease-in-out infinite}@keyframes royal-presence{50%{filter:brightness(1.1) drop-shadow(0 0 8px #733fb855)}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}.composer .row{gap:7px}#historyMessages{max-height:45vh;overflow:auto}.who{color:var(--gold)}
'''
s=s.replace('</style>',css+'</style>');p.write_text(s)
p=root/'server.py';s=p.read_text().replace("if self.path=='/foundry':", "if self.path=='/record-action':\n                if LOCK.locked(): raise ValueError('Wait for the current reply.')\n                hp=history(d['project']);ms=json.loads(hp.read_text()) if hp.exists() else []\n                ms.extend([{'role':'user','content':d['message']},{'role':'assistant','content':d['answer']}]);hp.write_text(json.dumps(ms));return self.send({'ok':True})\n            if self.path=='/foundry':");p.write_text(s)
