import assert from 'node:assert/strict';
import { appendReconciliation, evaluateConsent, parseConsent, type ConsentRecord, type ConsentRequest } from '../lib/participation/consent';
import { calculateAttribution, parseRoyaltyLedger, readFixedCreationObligations, readRoyaltyLedger, type RoyaltyLedger, type Adjustment } from '../lib/participation/royalties';
import { resolvePlatformIdentity } from '../lib/platform-identity';

let checks = 0;
function test(name: string, run: () => void) { try { run(); checks++; } catch (error) { throw new Error(name, { cause: error }); } }
const start = '2026-01-01T00:00:00.000Z', end = '2027-01-01T00:00:00.000Z', now = '2026-06-01T00:00:00.000Z';
const scope = { assetDigest: `sha256:${'0'.repeat(64)}`, contextId: 'context-001', audienceId: 'audience-001', providerId: 'provider-001', sublicensing: 'unknown' as const, assetId: 'asset-001', assetVersion: 'v1', productId: 'product-001', use: 'display', territory: 'territory-001', channel: 'channel-001', startsAt: start, endsAt: end, aiGeneration: 'unknown' as const, voiceCloning: 'denied' as const, training: 'unknown' as const };
function consent(): ConsentRecord { return { id: 'consent-001', participantId: 'participant-001', tenantId: 'tenant-001', status: 'executed', agreementEvidenceRefs: ['agreement-001'], participantSignatureRef: 'signature-001', entitySignatureRef: 'signature-002', materialApprovalRef: 'approval-001', rightsReviewRef: 'review-001', participantClass: 'adult', minorLinked: 'no', thirdPartyRights: 'cleared', scope: { ...scope }, existingCustomerContinuation: null }; }
function request(): ConsentRequest { return { assetDigest: scope.assetDigest, contextId: scope.contextId, audienceId: scope.audienceId, providerId: scope.providerId, sublicensing: 'not_requested', tenantId: 'tenant-001', participantId: 'participant-001', assetId: scope.assetId, assetVersion: 'v1', productId: scope.productId, use: 'display', territory: scope.territory, channel: scope.channel, at: now, aiGeneration: 'not_requested', voiceCloning: 'not_requested', training: 'not_requested', customerCohortRef: null }; }
function ledger(): RoyaltyLedger { return {
  schemaVersion: '1', collections: [{ transactionId: 'transaction-001', sourceReceiptRef: 'receipt-001', tenantId: 'tenant-001', currency: 'USD', status: 'collected', collectedAt: now, grossCents: 11000, allocationPolicyRef: 'allocation-policy-001', allocations: [{ id: 'allocation-001', productId: 'product-001', sourceId: 'source-001', grossCents: 11000, deductions: [{ id: 'tax-001', sourceItemRef: 'tax-source-001', kind: 'sales_tax', cents: 1000 }, { id: 'fee-001', sourceItemRef: 'fee-source-001', kind: 'payment_fee', cents: 300 }] }] }], adjustments: [],
  schedules: [{ id: 'schedule-001', tenantId: 'tenant-001', participantId: 'participant-001', productId: 'product-001', sourceId: 'source-001', status: 'executed', revokedAt: null, agreementEvidenceRefs: ['agreement-001'], participantSignatureRef: 'signature-001', entitySignatureRef: 'signature-002', contributionEvidenceRefs: ['contribution-001'], rightsEvidenceRefs: ['rights-001'], startsAt: start, endsAt: end, currency: 'USD', deductionPolicyId: 'deductions-001', allowedFeeKinds: ['payment_fee'], compensationPolicyId: 'compensation-001', stacking: 'combined', components: [{ id: 'component-001', kind: 'combined', basisPoints: 700 }], rounding: 'half_up_per_allocation', adjustmentPolicyRef: 'adjustments-001' }],
}; }
function refund(): Adjustment { return { eventId: 'event-001', sourceEventRef: 'event-source-001', transactionId: 'transaction-001', allocationId: 'allocation-001', recordedAt: '2026-07-01T00:00:00.000Z', kind: 'refund', principalOffsetCents: 0, principalCents: 5000, taxReturnedCents: 500, feeReversals: [] }; }
function rejectMutation(name: string, mutate: (l: RoyaltyLedger) => void) { test(name, () => { const l = ledger(); mutate(l); assert.throws(() => calculateAttribution(l)); }); }

test('Matching recorded consent never authorizes execution', () => { const r = evaluateConsent(consent(), request()); assert.equal(r.matchesRecordedScope, true); assert.equal(r.authorizesExecution, false); });
for (const status of ['unknown', 'draft', 'revoked', 'expired'] as const) test(`Deny consent ${status}`, () => { const c = consent(); c.status = status; assert.equal(evaluateConsent(c, request()).matchesRecordedScope, false); });
for (const key of ['participantSignatureRef', 'entitySignatureRef', 'materialApprovalRef', 'rightsReviewRef'] as const) test(`Deny absent ${key}`, () => { const c = consent(); c[key] = null; assert.equal(evaluateConsent(c, request()).matchesRecordedScope, false); });
for (const key of ['assetId', 'assetVersion', 'productId', 'use', 'territory', 'channel', 'tenantId', 'participantId', 'contextId', 'audienceId', 'providerId'] as const) test(`Deny mismatched ${key}`, () => { const q = request(); q[key] = 'mismatch'; assert.equal(evaluateConsent(consent(), q).matchesRecordedScope, false); });
for (const key of ['aiGeneration', 'voiceCloning', 'training', 'sublicensing'] as const) test(`Separate express ${key} permission`, () => { const q = request(), c = consent(); q[key] = 'requested'; assert.equal(evaluateConsent(c, q).matchesRecordedScope, false); c.scope[key] = 'approved'; assert.equal(evaluateConsent(c, q).matchesRecordedScope, true); });
test('End exclusive and no retroactive scope', () => { for (const at of [end, '2025-12-31T23:59:59.999Z']) assert.equal(evaluateConsent(consent(), { ...request(), at }).matchesRecordedScope, false); });
test('Minors, unknown age and unresolved third-party rights need separate review', () => { for (const participantClass of ['minor', 'unknown'] as const) assert.equal(evaluateConsent({ ...consent(), participantClass }, request()).matchesRecordedScope, false); assert.equal(evaluateConsent({ ...consent(), thirdPartyRights: 'unresolved' }, request()).matchesRecordedScope, false); });
test('Continuation requires explicit cohort and distinct term', () => { const c = consent(), q = request(); q.customerCohortRef = 'cohort-001'; q.at = '2027-06-01T00:00:00.000Z'; assert.equal(evaluateConsent(c, q).matchesRecordedScope, false); c.existingCustomerContinuation = { scope: { ...scope, endsAt: '2028-01-01T00:00:00.000Z' }, agreementEvidenceRefs: ['continuation-001'], customerCohortRef: 'cohort-001', status: 'approved' }; assert.equal(evaluateConsent(c, q).matchesRecordedScope, true); assert.equal(evaluateConsent(c, { ...q, customerCohortRef: null }).matchesRecordedScope, false); });
test('Malformed JSON and unknown keys rejected', () => { for (const json of ['{', 'null', '[]', '{"__proto__":{}}', '1e999']) assert.throws(() => parseConsent(json)); assert.throws(() => parseConsent(JSON.stringify({ ...consent(), approved: true }))); assert.throws(() => parseRoyaltyLedger('{')); });
test('Invalid date, fractional fields and huge input rejected', () => { assert.throws(() => parseConsent(JSON.stringify({ ...consent(), scope: { ...scope, endsAt: '2027-02-30T00:00:00.000Z' } }))); assert.throws(() => parseRoyaltyLedger(' '.repeat(250001))); });
test('Append preserves prior promise and conflict evidence', () => { const e = { id: 'record-001', participantId: 'participant-001', tenantId: 'tenant-001', recordedAt: now, kind: 'existing_promise', sourceEvidenceRefs: ['source-001'], relatedRecordIds: [], resolution: 'unreviewed' }; const history = [e]; const result = appendReconciliation(history, { ...e, id: 'record-002', kind: 'review', relatedRecordIds: [e.id], resolution: 'conflict' }); assert.equal(history.length, 1); assert.deepEqual(result[0], e); assert.throws(() => appendReconciliation(history, e)); assert.throws(() => appendReconciliation(history, { ...e, id: 'record-003', relatedRecordIds: ['missing'] })); });

test('Synthetic actual calculation and projected separation', () => { const l = ledger(); assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, 679); l.collections[0].status = 'projected'; const result = calculateAttribution(l); assert.deepEqual(result.lines, []); assert.deepEqual(result.excludedProjectedTransactionIds, ['transaction-001']); });
test('Refund principal and tax never deducted twice', () => { const l = ledger(); l.adjustments = [refund()]; const r = calculateAttribution(l).lines[0]; assert.equal(r.remainingEligibleCents, 4700); assert.equal(r.calculatedRoyaltyCents, 329); assert.equal(r.adjustmentDeltaCents, -350); assert.equal(r.taxReturnedCents, 500); });
test('Full refund gives zero without negative payout', () => { const l = ledger(); l.adjustments = [{ ...refund(), principalCents: 10000, taxReturnedCents: 1000 }]; const r = calculateAttribution(l); assert.equal(r.lines[0].calculatedRoyaltyCents, 0); assert.equal(r.approvedPayableCents, null); assert.equal(r.verifiedPaidCents, null); assert.equal(r.authorizesExecution, false); });
test('Fee reversal increases retained eligible base once', () => { const l = ledger(); l.adjustments = [{ ...refund(), feeReversals: [{ deductionId: 'fee-001', cents: 150 }] }]; assert.equal(calculateAttribution(l).lines[0].remainingEligibleCents, 4850); });
test('Refund and chargeback can cover disjoint principal ranges', () => { const l = ledger(); l.adjustments = [refund(), { ...refund(), eventId: 'event-002', sourceEventRef: 'event-source-002', kind: 'chargeback', principalOffsetCents: 5000 }]; assert.equal(calculateAttribution(l).lines[0].remainingEligibleCents, 0); });
rejectMutation('Duplicate transaction', l => l.collections.push(structuredClone(l.collections[0])));
rejectMutation('Duplicate receipt under new transaction', l => l.collections.push({ ...structuredClone(l.collections[0]), transactionId: 'transaction-002' }));
rejectMutation('Duplicate deductions', l => l.collections[0].allocations[0].deductions.push({ ...l.collections[0].allocations[0].deductions[1] }));
rejectMutation('Duplicate deduction provenance', l => l.collections[0].allocations[0].deductions.push({ ...l.collections[0].allocations[0].deductions[1], id: 'fee-002' }));
rejectMutation('Fractions', l => { l.collections[0].grossCents = 1.1; });
rejectMutation('Unsafe integer', l => { l.collections[0].grossCents = Number.MAX_SAFE_INTEGER + 1; });
rejectMutation('Nonfinite', l => { l.collections[0].grossCents = Infinity; });
rejectMutation('Negative', l => { l.collections[0].grossCents = -1; });
rejectMutation('Invalid basis points', l => { l.schedules[0].components[0].basisPoints = 10001; });
rejectMutation('Duplicate adjustment', l => { l.adjustments = [refund(), refund()]; });
rejectMutation('Refund principal excess', l => { l.adjustments = [{ ...refund(), principalCents: 10001 }]; });
rejectMutation('Overlapping refund and chargeback despite sum within gross', l => { l.adjustments = [refund(), { ...refund(), eventId: 'event-002', sourceEventRef: 'event-source-002', kind: 'chargeback' }]; });
rejectMutation('Tax refund excess', l => { l.adjustments = [{ ...refund(), taxReturnedCents: 1001 }]; });
rejectMutation('Fee reversal excess', l => { l.adjustments = [{ ...refund(), feeReversals: [{ deductionId: 'fee-001', cents: 301 }] }]; });
rejectMutation('Tax cannot be fee reversal', l => { l.adjustments = [{ ...refund(), feeReversals: [{ deductionId: 'tax-001', cents: 10 }] }]; });
rejectMutation('Unknown adjustment source', l => { l.adjustments = [{ ...refund(), transactionId: 'missing' }]; });
rejectMutation('Projection cannot be refunded', l => { l.collections[0].status = 'projected'; l.adjustments = [refund()]; });
rejectMutation('Allocation overcount', l => { l.collections[0].allocations.push({ id: 'allocation-002', productId: 'product-002', sourceId: 'source-002', grossCents: 1, deductions: [] }); });
rejectMutation('Missing bundle remainder', l => { l.collections[0].allocations[0].grossCents--; });
rejectMutation('Overlapping schedule', l => { l.schedules.push({ ...l.schedules[0], id: 'schedule-002' }); });
rejectMutation('Blank executed agreement evidence', l => { l.schedules[0].agreementEvidenceRefs = []; });
rejectMutation('Stacking above 100%', l => { l.schedules[0].stacking = 'separate'; l.schedules[0].components = [{ id: 'a', kind: 'likeness', basisPoints: 6000 }, { id: 'b', kind: 'product_creation', basisPoints: 6000 }]; });
test('Bundle remainder explicit and only targeted allocation earns', () => { const l = ledger(); l.collections[0].grossCents += 2000; l.collections[0].allocations.push({ id: 'remainder', productId: null, sourceId: null, grossCents: 2000, deductions: [] }); assert.equal(calculateAttribution(l).lines.length, 1); assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, 679); });
test('Source and tenant matching are exact', () => { for (const key of ['tenantId', 'sourceId', 'productId'] as const) { const l = ledger(); l.schedules[0][key] = 'other'; assert.equal(calculateAttribution(l).lines.length, 0); } });
test('Revoked or draft royalty schedules do not accrue', () => { for (const status of ['revoked', 'draft'] as const) { const l = ledger(); l.schedules[0].status = status; l.schedules[0].revokedAt = status === 'revoked' ? now : null; assert.equal(calculateAttribution(l).lines.length, 0); } });
test('Explicit rounding and residual', () => { const l = ledger(); l.collections[0].grossCents = 5; l.collections[0].allocations[0].grossCents = 5; l.collections[0].allocations[0].deductions = []; l.schedules[0].components[0].basisPoints = 1000; assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, 1); assert.equal(calculateAttribution(l).lines[0].roundingResidualNumerator, '5000'); l.schedules[0].rounding = 'floor_per_allocation'; assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, 0); });
test('Half-up component overcount requires reconciliation', () => { const l = ledger(); l.collections[0].grossCents = 1; l.collections[0].allocations[0].grossCents = 1; l.collections[0].allocations[0].deductions = []; l.schedules[0].stacking = 'separate'; l.schedules[0].components = [{ id: 'a', kind: 'likeness', basisPoints: 5000 }, { id: 'b', kind: 'product_creation', basisPoints: 5000 }]; assert.throws(() => calculateAttribution(l)); });
test('BigInt intermediate multiplication remains exact', () => { const l = ledger(), gross = Number.MAX_SAFE_INTEGER; l.collections[0].grossCents = gross; l.collections[0].allocations[0].grossCents = gross; l.collections[0].allocations[0].deductions = []; l.schedules[0].components[0].basisPoints = 10000; assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, gross); });
test('Fixed obligation IDs prevent per-sale repeat', () => { const fixed = { id: 'fixed-001', tenantId: 'tenant-001', participantId: 'participant-001', productId: 'product-001', obligationSourceRef: 'fixed-source-001', agreementEvidenceRefs: ['agreement-001'], status: 'executed', currency: 'USD', amountCents: 100, dueAt: end }; assert.equal(readFixedCreationObligations([fixed]).length, 1); assert.throws(() => readFixedCreationObligations([fixed, { ...fixed, id: 'fixed-002' }])); });
test('Strict ledger roundtrip; object unknown fields blocked', () => { assert.deepEqual(parseRoyaltyLedger(JSON.stringify(ledger())), ledger()); assert.throws(() => readRoyaltyLedger({ ...ledger(), approvePayment: true })); });
test('Production identity remains fail closed with forged headers', () => { const old = process.env.NODE_ENV; try { (process.env as Record<string, string | undefined>).NODE_ENV = 'production'; const r = resolvePlatformIdentity(new Request('https://example.invalid', { headers: { 'x-tay-dev-user': 'user-001', 'x-tay-dev-tenant': 'tenant-001', 'x-tay-dev-role': 'owner', 'x-tay-dev-session': 'session-001' } })); assert.equal(r.ok, false); assert.equal(r.identity, null); } finally { (process.env as Record<string, string | undefined>).NODE_ENV = old; } });

test('Revocation preserves historical accrued calculation and later corrections', () => { const l = ledger(); l.schedules[0].status = 'revoked'; l.schedules[0].revokedAt = '2026-06-02T00:00:00.000Z'; l.adjustments = [refund()]; assert.equal(calculateAttribution(l).lines[0].calculatedRoyaltyCents, 329); });
test('Digest must match exact asset bytes reference', () => { assert.equal(evaluateConsent(consent(), { ...request(), assetDigest: `sha256:${'1'.repeat(64)}` }).matchesRecordedScope, false); });
test('Minor-linked and unknown review states block separately', () => { for (const minorLinked of ['yes', 'unknown'] as const) assert.equal(evaluateConsent({ ...consent(), minorLinked }, request()).matchesRecordedScope, false); });
test('Refund cannot conceal original over-allocation across participants', () => { const l = ledger(); l.schedules[0].components[0].basisPoints = 10000; l.schedules.push({ ...structuredClone(l.schedules[0]), id: 'schedule-002', participantId: 'participant-002' }); l.adjustments = [{ ...refund(), principalCents: 10000, taxReturnedCents: 1000 }]; assert.throws(() => calculateAttribution(l)); });
test('Historical reconciliation links must reference earlier records', () => { const e = { id: 'record-001', participantId: 'participant-001', tenantId: 'tenant-001', recordedAt: now, kind: 'existing_promise', sourceEvidenceRefs: ['source-001'], relatedRecordIds: ['missing'], resolution: 'unreviewed' }; assert.throws(() => appendReconciliation([e], { ...e, id: 'record-002', relatedRecordIds: ['record-001'] })); });
test('Sparse evidence arrays cannot satisfy consent or royalty prerequisites', () => { const c = consent(); c.agreementEvidenceRefs = new Array(1); assert.equal(evaluateConsent(c, request()).matchesRecordedScope, false); for (const key of ['agreementEvidenceRefs', 'rightsEvidenceRefs', 'contributionEvidenceRefs'] as const) { const l = ledger(); l.schedules[0][key] = new Array(1); assert.throws(() => calculateAttribution(l)); } });
test('Split refunds use cumulative rounded entitlement without penny drift', () => {
  const l = ledger();
  l.collections[0].grossCents = 5; l.collections[0].allocations[0].grossCents = 5;
  l.collections[0].allocations[0].deductions = []; l.schedules[0].components[0].basisPoints = 1000;
  const original = calculateAttribution(l).lines[0].calculatedRoyaltyCents;
  l.adjustments = [{ ...refund(), principalCents: 1, taxReturnedCents: 0 }];
  const first = calculateAttribution(l).lines[0].calculatedRoyaltyCents;
  l.adjustments.push({ ...refund(), eventId: 'event-002', sourceEventRef: 'event-source-002', principalOffsetCents: 1, principalCents: 1, taxReturnedCents: 0 });
  const second = calculateAttribution(l).lines[0].calculatedRoyaltyCents;
  assert.deepEqual([original, first - original, second - first], [1, -1, 0]);
});
console.log(`Participation contract: ${checks} checks passed (synthetic records only; no external actions).`);
